---
abstract: 'Ship your TestML version'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-TestMLIncluder
requires:
  Dist::Zilla::Plugin::ModuleIncluder: 0.004
resources:
  bugtracker: https://github.com/ingydotnet/dist-zilla-plugin-testmlincluder-pm/issues
  homepage: https://github.com/ingydotnet/dist-zilla-plugin-testmlincluder-pm
  repository: https://github.com/ingydotnet/dist-zilla-plugin-testmlincluder-pm.git
version: 0.01
